### PR TITLE
Static HTML for home pages [issue 15]

### PR DESCRIPTION
**Pull request by jedpimentel**

### CODE REVIEW

**Review by muigaiunaka — CHANGES_REQUESTED** [review]
line 9 through line 17: place Button in `<a>` !!
```
<a href="">
     <button>
          Week
     </button>
</a>
```
line 20 through line 30 
- no nav or a around `<i>`
- the up & down arrows are not link

**Review by muigaiunaka — CHANGES_REQUESTED** [review]
Let's get Arnold's edits into this before I merge !

**Comment by jedpimentel** [comment]
I checked Arnolds changes, they should be okay,,

**Review by muigaiunaka — APPROVED** [review]
Glorious, good work yall.

**Comment by jedpimentel** [comment]
I just noticed the changes for iss32 piggybacked onto here,

**Pull request merged**
